default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: coronavirus_development

test:
  <<: *default
  database: coronavirus_test

production:
  <<: *default
  database: coronavirus_production
  username: coronavirus
  password: <%= ENV['MCALILLY_DATABASE_PASSWORD'] %>
